const wmsDropdownItems = [
  "Replishment Requests",
  "Purchase Requests",
  "Purchase Orders",
  "Recieving",
  "Returns",
];

const wmsTabsData = [
  {
    name: "Replishment Requests", tabs: [], allTabData:
      [
        {
          data: [
            {
              x: "Miles",
              dateTime: "08 - 03 - 2021 04:18",
              itemsInfo: "N/A",
              generatedBy: "William",
              reason: "Emma@gmail.com",
              transactionID: "MRNRID103211309",
            },
            {
              requestId: "Emma",
              dateTime: "08 - 03 - 2021 04:18",
              itemsInfo: "N/A",
              generatedBy: "William ",
              reason: "Emma@gmail.com",
              transactionID: "MRNRID103211309",
            },
            {
              requestId: "Watson",
              dateTime: "08 - 03 - 2021 04:18",
              itemsInfo: "N/A",
              generatedBy: "William ",
              reason: "Emma@gmail.com",
              transactionID: "MRNRID103211309",
            },
          ],
          heading: [
            "Request Id",
            "Date / Time",
            "Items Info",
            "Generated by",
            "Reason",
            "Transaction ID",
            "Action",
          ],
          tableDataKeys: [
            "requestId",
            "dateTime",
            "itemsInfo",
            "generatedBy",
            "reason",
            "transactionID",
          ],
          actions: {
            view: true,
          },
        },
      ],
    endpointURL: "/getHistoryEDR?info=EDR"
  },
  {
    name: "Purchase Requests", tabs: [],
    allTabData: [
      {
        data: [
          {
            x: "Miles",
            dateTime: "08 - 03 - 2021 04:18",
            itemsInfo: "N/A",
            generatedBy: "William",
            reason: "Emma@gmail.com",
            approvedBy: "",
            transactionID: "MRNRID103211309",
          },
          {
            requestId: "Emma",
            dateTime: "08 - 03 - 2021 04:18",
            itemsInfo: "N/A",
            generatedBy: "William ",
            reason: "Emma@gmail.com",
            approvedBy: "",
            transactionID: "MRNRID103211309",
          },
          {
            requestId: "Watson",
            dateTime: "08 - 03 - 2021 04:18",
            itemsInfo: "N/A",
            generatedBy: "William ",
            reason: "Emma@gmail.com",
            approvedBy: "",
            transactionID: "MRNRID103211309",
          },
        ],
        heading: [
          "Request Id",
          "Date / Time",
          "Items Info",
          "Generated by",
          "Reason",
          "Approved By",
          "Transaction ID",
          "Action",
        ],
        tableDataKeys: [
          "requestId",
          "dateTime",
          "itemsInfo",
          "generatedBy",
          "reason",
          "approvedBy",
          "transactionID",
        ],
        actions: {
          view: true,
        },
      },
    ], endpointURL: "/getHistoryIPR?info=IPR"
  },
  {
    name: "Purchase Orders", tabs: [], allTabData: [
      {
        data: [
          {
            orderId: "",
            dateTime: "",
            itemsInfo: "",
            generatedBy: "",
            reason: "",
            vendor: "",
            approvedBy: "",
            transactionID: ""
          }
        ],
        heading: [
          "Order Id",
          "Date / Time",
          "Items Info",
          "Generated by",
          "Reason",
          "Vendor",
          "Approved by",
          "Transaction ID",
          "Action",
        ],
        tableDataKeys: [
          "orderId",
          "dateTime",
          "itemsInfo",
          "generatedBy",
          "reason",
          "vendor",
          "approvedBy",
          "transactionID",
        ],
        actions: {
          view: true,
        },
      },
    ], endpointURL: "/getHistoryIPR?info=IPR"
  },
  {
    name: "Recieving", tabs: [ "Internal", "External" ], allTabData: [
      {
        data: [
          {
            requestId: "",
            dateTime: "",
            itemsInfo: "",
            receivedBy: "",
            transactionID: "",
          }
        ],
        heading: [
          "Request Id",
          "Date / Time",
          "Items Info",
          "Recieved by",
          "Transaction ID",
          "Action",
        ],
        tableDataKeys: [
          "requestId",
          "dateTime",
          "itemsInfo",
          "receivedBy",
          "transactionID",
        ],
        actions: {
          view: true,
        },
      },
      {
        data: [
          {
            orderId: "",
            dateTime: "",
            itemsInfo: "",
            receivedBy: "",
            vendor: "",
            transactionID: "",
          }
        ],
        heading: [
          "Order Id",
          "Date / Time",
          "Items Info",
          "Recieved by",
          "Vendor",
          "Transaction ID",
          "Action",
        ],
        tableDataKeys: [
          "orderId",
          "dateTime",
          "itemsInfo",
          "receivedBy",
          "vendor",
          "transactionID",
        ],
        actions: {
          view: true,
        },
      },
    ], endpointURL: "/getHistoryIPR?info=IPR"
  },
  {
    name: "Returns", tabs: [ "Internal", "External" ], allTabData: [
      {
        data: [
          {
            requestID: "",
            dateTime: "",
            itemsInfo: "",
            receivedBy: "",
            returnedBy: "",
            reason: "",
            transactionID: ""
          }
        ],
        heading: [
          "Request Id",
          "Date / Time",
          "Items Info",
          "Recieved by",
          "Returned by",
          "Reason",
          "Transaction ID",
          "Action",
        ],
        tableDataKeys: [
          "requestID",
          "dateTime",
          "itemsInfo",
          "receivedBy",
          "returnedBy",
          "reason",
          "transactionID"
        ],
        actions: {
          view: true,
        },
      },
      {
        data: [
          {
            orderID: "",
            dateTime: "",
            patientInfo: "",
            vendor: "",
            returnedBy: "",
            reason: "",
            transactionID: ""
          }
        ],
        heading: [
          "Order Id",
          "Date / Time",
          "Items Info",
          "Vendor",
          "Returnd by",
          "Reason",
          "Transaction ID",
          "Action",
        ],
        tableDataKeys: [
          "orderID",
          "dateTime",
          "itemsInfo",
          "vendor",
          "returnedBy",
          "reason",
          "transactionID"
        ],
        actions: {
          view: true,
        },
      }
    ], endpointURL: "/getHistoryIPR?info=IPR"
  },
];

export default {
  wmsDropdownItems,
  wmsTabsData,
};
