const wmsDropdownItems = [
  "patients Assessment",
  "Patient Diagnosis",
  "RD Assessment & Diagnosis",
  "Insurance Claims",
  "EC Assessment & Diagnosis",
  "Patient Discharge",
  "Orders",
];

const wmsTabs = [
  "Replishment Requests",
  "Purchase Requests",
  "Purchase Orders",
  "Receiving",
  "Returns",
];

const innerTabs = ["Internal", "External"];

const wmsTableData = [
  {
    "Replishment Requests": {
      data: [
        {
          requestId: "requestId1",
          dateTime: "dateTime1",
          itemsInfo: "itemsInfo1",
          generatedBy: "generatedBy1",
          reason: "reason1",
          transactionId: "transactionId1",
        },
        {
          requestId: "requestId2",
          dateTime: "dateTime2",
          itemsInfo: "itemsInfo2",
          generatedBy: "generatedBy2",
          reason: "reason2",
          transactionId: "transactionId2",
        },
        {
          requestId: "requestId3",
          dateTime: "dateTime3",
          itemsInfo: "itemsInfo3",
          generatedBy: "generatedBy3",
          reason: "reason3",
          transactionId: "transactionId3",
        },
      ],
      heading: [
        "Request Id",
        "Date / Time",
        "Items Info",
        "Generated by",
        "Reason",
        "Transaction ID",
        " ",
      ],
      tableDataKeys: [
        "requestId",
        "dateTime",
        "itemsInfo",
        "generatedBy",
        "reason",
        "transactionId",
      ],
      actions: {
        view: true,
      },
      selected: true,
    },
  },
  {
    "Purchase Requests": {
      data: [
        {
          requestId: "requestId1",
          dateTime: "dateTime1",
          itemsInfo: "itemsInfo1",
          generatedBy: "generatedBy1",
          reason: "reason1",
          approvedBy: "approvedBy1",
          transactionId: "transactionId1",
        },
        {
          requestId: "requestId2",
          dateTime: "dateTime2",
          itemsInfo: "itemsInfo2",
          generatedBy: "generatedBy2",
          reason: "reason2",
          approvedBy: "approvedBy2",
          transactionId: "transactionId2",
        },
        {
          requestId: "requestId3",
          dateTime: "dateTime3",
          itemsInfo: "itemsInfo3",
          generatedBy: "generatedBy3",
          reason: "reason3",
          approvedBy: "approvedBy3",
          transactionId: "transactionId3",
        },
      ],
      heading: [
        "Request Id",
        "Date / Time",
        "Items Info",
        "Generated by",
        "Reason",
        "Approved By",
        "Transaction ID",
        " ",
      ],
      tableDataKeys: [
        "requestId",
        "dateTime",
        "itemsInfo",
        "generatedBy",
        "reason",
        "approvedBy",
        "transactionId",
      ],
      actions: {
        view: false,
      },
      selected: false,
    },
  },
  {
    "Purchase Orders": {
      data: [
        {
          orderId: "mrn1",
          dateTime: "patientName1",
          itemsInfo: "Insured1",
          generatedBy: "UnInsured1",
          reason: "CoverageDetails1",
          vendor: "vendor1",
          approvedBy: "approvedBy1",
          transactionId: "transactionId1",
        },
        {
          orderId: "mrn2",
          dateTime: "patientName2",
          itemsInfo: "Insured2",
          generatedBy: "UnInsured2",
          reason: "CoverageDetails2",
          vendor: "vendor2",
          approvedBy: "approvedBy2",
          transactionId: "transactionId2",
        },
        {
          orderId: "mrn3",
          dateTime: "patientName3",
          itemsInfo: "Insured3",
          generatedBy: "UnInsured3",
          reason: "CoverageDetails3",
          vendor: "vendor3",
          approvedBy: "approvedBy3",
          transactionId: "transactionId3",
        },
      ],
      heading: [
        "Order Id",
        "Date / Time",
        "Items Info",
        "Generated by",
        "Reason",
        "Vendor",
        "Approved by",
        "Transaction ID",
        " ",
      ],
      tableDataKeys: [
        "orderId",
        "dateTime",
        "itemsInfo",
        "generatedBy",
        "reason",
        "vendor",
        "approvedBy",
        "transactionId",
      ],
      actions: {
        view: false,
      },
      selected: false,
    },
  },
  {
    Receiving: {
      innerTabs: [
        {
          Internal: {
            data: [
              {
                requestId: "requestId1",
                dateTime: "dateTime1",
                itemsInfo: "itemsInfo1",
                receivedBy: "receivedBy1",
                transactionId: "transactionId1",
              },
              {
                requestId: "requestId2",
                dateTime: "dateTime2",
                itemsInfo: "itemsInfo2",
                receivedBy: "receivedBy2",
                transactionId: "transactionId2",
              },
              {
                requestId: "requestId3",
                dateTime: "dateTime3",
                itemsInfo: "itemsInfo3",
                receivedBy: "receivedBy3",
                transactionId: "transactionId3",
              },
            ],
            heading: [
              "Request Id",
              "Date / Time",
              "Items Info",
              "Received by",
              "Transaction ID",
              " ",
              " ",
            ],
            tableDataKeys: [
              "requestId",
              "dateTime",
              "itemsInfo",
              "receivedBy",
              "transactionId",
            ],
            actions: {
              view: false,
            },
          },
        },
        {
          External: {
            data: [
              {
                requestId: "requestId1",
                dateTime: "dateTime1",
                itemsInfo: "itemsInfo1",
                receivedBy: "receivedBy1",
                transactionId: "transactionId1",
              },
              {
                requestId: "requestId2",
                dateTime: "dateTime2",
                itemsInfo: "itemsInfo2",
                receivedBy: "receivedBy2",
                transactionId: "transactionId2",
              },
              {
                requestId: "requestId3",
                dateTime: "dateTime3",
                itemsInfo: "itemsInfo3",
                receivedBy: "receivedBy3",
                transactionId: "transactionId3",
              },
            ],
            heading: [
              "Order Id",
              "Date / Time",
              "Items Info",
              "Recieved by",
              "Vendor",
              "Transaction ID",
            ],
            tableDataKeys: [
              "orderId",
              "dateTime",
              "itemsInfo",
              "receivedBy",
              "vendor",
              "transactionId",
            ],
            actions: {
              view: false,
            },
          },
        },
      ],
      selected: false,
    },
  },
  {
    Returns: {
      innerTabs: [
        {
          Internal: {
            data: [
              {
                requestId: "requestId1",
                dateTime: "dateTime1",
                itemsInfo: "itemsInfo1",
                receivedBy: "receivedBy1",
                returnedBy: "returnedBy1",
                reason: "reason1",
                transactionId: "transactionId1",
              },
              {
                requestId: "requestId2",
                dateTime: "dateTime2",
                itemsInfo: "itemsInfo2",
                receivedBy: "receivedBy2",
                returnedBy: "returnedBy2",
                reason: "reason2",
                transactionId: "transactionId2",
              },
              {
                requestId: "requestId3",
                dateTime: "dateTime3",
                itemsInfo: "itemsInfo3",
                receivedBy: "receivedBy3",
                returnedBy: "returnedBy3",
                reason: "reason3",
                transactionId: "transactionId3",
              },
            ],
            heading: [
              "Request Id",
              "Date / Time",
              "Items Info",
              "Received by",
              "Returned by",
              "Reason",
              "Transaction ID",
              " ",
            ],
            tableDataKeys: [
              "requestId",
              "dateTime",
              "itemsInfo",
              "receivedBy",
              "returnedBy",
              "reason",
              "transactionId",
            ],
            actions: {
              view: false,
            },
          },
        },
        {
          External: {
            data: [
              {
                requestId: "requestId1",
                dateTime: "dateTime1",
                itemsInfo: "itemsInfo1",
                receivedBy: "receivedBy1",
                transactionId: "transactionId1",
              },
              {
                requestId: "requestId2",
                dateTime: "dateTime2",
                itemsInfo: "itemsInfo2",
                receivedBy: "receivedBy2",
                transactionId: "transactionId2",
              },
              {
                requestId: "requestId3",
                dateTime: "dateTime3",
                itemsInfo: "itemsInfo3",
                receivedBy: "receivedBy3",
                transactionId: "transactionId3",
              },
            ],
            heading: [
              "Order Id",
              "Date / Time",
              "Items Info",
              "Recieved by",
              "Returned By",
              "Reason",
              "Vendor",
              "Transaction ID",
            ],
            tableDataKeys: [
              "orderId",
              "dateTime",
              "itemsInfo",
              "receivedBy",
              "vendor",
              "transactionId",
            ],
            actions: {
              view: false,
            },
          },
        },
      ],
      selected: false,
    },
  },
];

export default {
  wmsDropdownItems,
  wmsTabs,
  wmsTableData,
  innerTabs,
};
